const music = [
  {
    category: "pop",
    title: "Deceiver",
    text: "Albert Gold, 2014",
    audio: "Albert Gold - Deceiver",
  },
  {
    category: "pop",
    title: "Vacation",
    text: "Harrison Wheeler, 2017",
    audio: "Harrison Wheeler - Vacation",
  },
  {
    category: "pop",
    title: "Good Together",
    text: "HONNE, 2016",
    audio: "HONNE - Good Together",
  },
  {
    category: "pop",
    title: "The Universe We Dreamt",
    text: "Matt DiMona, 2016",
    audio: "Matt DiMona - The Universe We Dreamt",
  },
  {
    category: "pop",
    title: "West Coast",
    text: "Pretty Sister, 2016",
    audio: "Pretty Sister - West Coast",
  },
  {
    category: "pop",
    title: "All I Need",
    text: "Scoop X On Planets, 2013",
    audio: "Scoop X On Planets - All I Need",
  },
  {
    category: "pop",
    title: "San Francisco Street",
    text: "Sun Rai, 2013",
    audio: "Sun Rai - San Francisco Street",
  },
  {
    category: "pop",
    title: "Fallout",
    text: "Young Summer, 2016",
    audio: "Young Summer - Fallout",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Laika",
    text: "ADOY, 2017",
    audio: "ADOY - Laika",
  },
  {
    category: "indie",
    title: "Wonder",
    text: "ADOY, 2018",
    audio: "ADOY - Wonder",
  },
  {
    category: "chill",
    title: "SARA SMILE",
    text: "YERIN, 2017",
    audio: "YERIN - SARA SMILE",
  },
];
